### ISSUE TITLE
Transform methods returning meshes to classes as it was done for lenses and cylinder

### ISSUE THREAD

**Issue by Mateasek** [mattngc/raysect_mayavi#2]
I would like to transform rest of the methods constructing geometric primitives and mesh primitive to classes as it was done for cylindrical primitives (lenses, cylinder). There are two reasons. Now there is different approach taken for primitives, which I think could be confusion and also ot will allow the plotting mechanism to be changed to better treat different "objects" as for example primitives and ray trajectories. Each class can hold metadata about its plot properties and can add itself to a figure using preferred plotting function.

**Comment by mattngc** [comment]
Hey, I think this sounds sensible. No harm in trying it.

**Comment by mattngc** [comment]
This has been resolved now in PR #6
